name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting, please search existing issues to avoid duplicates.

  - type: textarea
    id: problem
    attributes:
      label: Problem this solves
      description: Describe the problem or limitation you are running into.
      placeholder: "I am trying to do X but the service does not support..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the change you would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: List any alternative solutions or workarounds you have considered.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or references that may help.
