// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package sqlcpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :exec
INSERT INTO applications (id, name, description, platforms, config, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateApplicationParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Platforms   []byte             `json:"platforms"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) error {
	_, err := q.db.Exec(ctx, createApplication,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Platforms,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getAllApplications = `-- name: GetAllApplications :many
SELECT id, name, description, platforms, config, created_at, updated_at
FROM applications
ORDER BY name
`

func (q *Queries) GetAllApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.Query(ctx, getAllApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Platforms,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, name, description, platforms, config, created_at, updated_at
FROM applications
WHERE id = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Platforms,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE applications
SET name = $2, description = $3, platforms = $4, config = $5, updated_at = $6
WHERE id = $1
`

type UpdateApplicationParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Platforms   []byte             `json:"platforms"`
	Config      []byte             `json:"config"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.Exec(ctx, updateApplication,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Platforms,
		arg.Config,
		arg.UpdatedAt,
	)
	return err
}
