// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package sqlcpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getAllApplications = `-- name: GetAllApplications :many
SELECT id, name, description, platforms, config, created_at, updated_at
FROM applications
ORDER BY name
`

func (q *Queries) GetAllApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.Query(ctx, getAllApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Platforms,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, name, description, platforms, config, created_at, updated_at
FROM applications
WHERE id = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Platforms,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationsPaged = `-- name: GetApplicationsPaged :many
SELECT id, name, description, platforms, config, created_at, updated_at,
       COUNT(*) OVER() AS total_count
FROM applications
ORDER BY name
LIMIT $1::bigint OFFSET $2::bigint
`

type GetApplicationsPagedParams struct {
	Column1 int64 `json:"column_1"`
	Column2 int64 `json:"column_2"`
}

type GetApplicationsPagedRow struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Platforms   []byte             `json:"platforms"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TotalCount  int64              `json:"total_count"`
}

func (q *Queries) GetApplicationsPaged(ctx context.Context, arg GetApplicationsPagedParams) ([]GetApplicationsPagedRow, error) {
	rows, err := q.db.Query(ctx, getApplicationsPaged, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetApplicationsPagedRow{}
	for rows.Next() {
		var i GetApplicationsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Platforms,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApplication = `-- name: UpsertApplication :exec
INSERT INTO applications (id, name, description, platforms, config, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    platforms = EXCLUDED.platforms,
    config = EXCLUDED.config,
    updated_at = EXCLUDED.updated_at
`

type UpsertApplicationParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Platforms   []byte             `json:"platforms"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertApplication(ctx context.Context, arg UpsertApplicationParams) error {
	_, err := q.db.Exec(ctx, upsertApplication,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Platforms,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
