// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcpg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"key_hash"`
	Prefix      string             `json:"prefix"`
	Permissions []byte             `json:"permissions"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Application struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Platforms   []byte             `json:"platforms"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Release struct {
	ID             string             `json:"id"`
	ApplicationID  string             `json:"application_id"`
	Version        string             `json:"version"`
	Platform       string             `json:"platform"`
	Architecture   string             `json:"architecture"`
	DownloadUrl    string             `json:"download_url"`
	Checksum       string             `json:"checksum"`
	ChecksumType   string             `json:"checksum_type"`
	FileSize       int64              `json:"file_size"`
	ReleaseNotes   pgtype.Text        `json:"release_notes"`
	ReleaseDate    pgtype.Timestamptz `json:"release_date"`
	Required       bool               `json:"required"`
	MinimumVersion pgtype.Text        `json:"minimum_version"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
