// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package sqlcpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases
WHERE application_id = $1 AND version = $2 AND platform = $3 AND architecture = $4
`

type DeleteReleaseParams struct {
	ApplicationID string `json:"application_id"`
	Version       string `json:"version"`
	Platform      string `json:"platform"`
	Architecture  string `json:"architecture"`
}

func (q *Queries) DeleteRelease(ctx context.Context, arg DeleteReleaseParams) error {
	_, err := q.db.Exec(ctx, deleteRelease,
		arg.ApplicationID,
		arg.Version,
		arg.Platform,
		arg.Architecture,
	)
	return err
}

const getApplicationStats = `-- name: GetApplicationStats :one
SELECT
    COUNT(*) AS total_releases,
    COUNT(*) FILTER (WHERE r1.required) AS required_releases,
    COUNT(DISTINCT r1.platform) AS platform_count,
    MAX(r1.release_date) AS latest_release_date,
    (
        SELECT r2.version FROM releases r2
        WHERE r2.application_id = $1
        ORDER BY r2.version_major DESC, r2.version_minor DESC, r2.version_patch DESC,
                 (r2.version_pre_release IS NULL) DESC,
                 r2.version_pre_release ASC
        LIMIT 1
    ) AS latest_version
FROM releases r1 WHERE r1.application_id = $1
`

type GetApplicationStatsRow struct {
	TotalReleases     int64       `json:"total_releases"`
	RequiredReleases  int64       `json:"required_releases"`
	PlatformCount     int64       `json:"platform_count"`
	LatestReleaseDate interface{} `json:"latest_release_date"`
	LatestVersion     string      `json:"latest_version"`
}

func (q *Queries) GetApplicationStats(ctx context.Context, applicationID string) (GetApplicationStatsRow, error) {
	row := q.db.QueryRow(ctx, getApplicationStats, applicationID)
	var i GetApplicationStatsRow
	err := row.Scan(
		&i.TotalReleases,
		&i.RequiredReleases,
		&i.PlatformCount,
		&i.LatestReleaseDate,
		&i.LatestVersion,
	)
	return i, err
}

const getLatestStableRelease = `-- name: GetLatestStableRelease :one
SELECT id, application_id, version, platform, architecture, download_url,
       checksum, checksum_type, file_size, release_notes, release_date,
       required, minimum_version, metadata, created_at,
       version_major, version_minor, version_patch, version_pre_release
FROM releases
WHERE application_id = $1 AND platform = $2 AND architecture = $3
  AND version_pre_release IS NULL
ORDER BY version_major DESC, version_minor DESC, version_patch DESC
LIMIT 1
`

type GetLatestStableReleaseParams struct {
	ApplicationID string `json:"application_id"`
	Platform      string `json:"platform"`
	Architecture  string `json:"architecture"`
}

func (q *Queries) GetLatestStableRelease(ctx context.Context, arg GetLatestStableReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, getLatestStableRelease, arg.ApplicationID, arg.Platform, arg.Architecture)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.Platform,
		&i.Architecture,
		&i.DownloadUrl,
		&i.Checksum,
		&i.ChecksumType,
		&i.FileSize,
		&i.ReleaseNotes,
		&i.ReleaseDate,
		&i.Required,
		&i.MinimumVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.VersionPreRelease,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, application_id, version, platform, architecture, download_url,
       checksum, checksum_type, file_size, release_notes, release_date,
       required, minimum_version, metadata, created_at,
       version_major, version_minor, version_patch, version_pre_release
FROM releases
WHERE application_id = $1 AND version = $2 AND platform = $3 AND architecture = $4
`

type GetReleaseParams struct {
	ApplicationID string `json:"application_id"`
	Version       string `json:"version"`
	Platform      string `json:"platform"`
	Architecture  string `json:"architecture"`
}

func (q *Queries) GetRelease(ctx context.Context, arg GetReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, getRelease,
		arg.ApplicationID,
		arg.Version,
		arg.Platform,
		arg.Architecture,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.Platform,
		&i.Architecture,
		&i.DownloadUrl,
		&i.Checksum,
		&i.ChecksumType,
		&i.FileSize,
		&i.ReleaseNotes,
		&i.ReleaseDate,
		&i.Required,
		&i.MinimumVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.VersionPreRelease,
	)
	return i, err
}

const getReleaseByID = `-- name: GetReleaseByID :one
SELECT id, application_id, version, platform, architecture, download_url,
       checksum, checksum_type, file_size, release_notes, release_date,
       required, minimum_version, metadata, created_at,
       version_major, version_minor, version_patch, version_pre_release
FROM releases
WHERE id = $1
`

func (q *Queries) GetReleaseByID(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseByID, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.Platform,
		&i.Architecture,
		&i.DownloadUrl,
		&i.Checksum,
		&i.ChecksumType,
		&i.FileSize,
		&i.ReleaseNotes,
		&i.ReleaseDate,
		&i.Required,
		&i.MinimumVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.VersionPreRelease,
	)
	return i, err
}

const getReleasesByAppID = `-- name: GetReleasesByAppID :many
SELECT id, application_id, version, platform, architecture, download_url,
       checksum, checksum_type, file_size, release_notes, release_date,
       required, minimum_version, metadata, created_at,
       version_major, version_minor, version_patch, version_pre_release
FROM releases
WHERE application_id = $1
ORDER BY release_date DESC
`

func (q *Queries) GetReleasesByAppID(ctx context.Context, applicationID string) ([]Release, error) {
	rows, err := q.db.Query(ctx, getReleasesByAppID, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Version,
			&i.Platform,
			&i.Architecture,
			&i.DownloadUrl,
			&i.Checksum,
			&i.ChecksumType,
			&i.FileSize,
			&i.ReleaseNotes,
			&i.ReleaseDate,
			&i.Required,
			&i.MinimumVersion,
			&i.Metadata,
			&i.CreatedAt,
			&i.VersionMajor,
			&i.VersionMinor,
			&i.VersionPatch,
			&i.VersionPreRelease,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleasesByPlatformArch = `-- name: GetReleasesByPlatformArch :many
SELECT id, application_id, version, platform, architecture, download_url,
       checksum, checksum_type, file_size, release_notes, release_date,
       required, minimum_version, metadata, created_at,
       version_major, version_minor, version_patch, version_pre_release
FROM releases
WHERE application_id = $1 AND platform = $2 AND architecture = $3
ORDER BY release_date DESC
`

type GetReleasesByPlatformArchParams struct {
	ApplicationID string `json:"application_id"`
	Platform      string `json:"platform"`
	Architecture  string `json:"architecture"`
}

func (q *Queries) GetReleasesByPlatformArch(ctx context.Context, arg GetReleasesByPlatformArchParams) ([]Release, error) {
	rows, err := q.db.Query(ctx, getReleasesByPlatformArch, arg.ApplicationID, arg.Platform, arg.Architecture)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Version,
			&i.Platform,
			&i.Architecture,
			&i.DownloadUrl,
			&i.Checksum,
			&i.ChecksumType,
			&i.FileSize,
			&i.ReleaseNotes,
			&i.ReleaseDate,
			&i.Required,
			&i.MinimumVersion,
			&i.Metadata,
			&i.CreatedAt,
			&i.VersionMajor,
			&i.VersionMinor,
			&i.VersionPatch,
			&i.VersionPreRelease,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelease = `-- name: UpsertRelease :exec
INSERT INTO releases (
    id, application_id, version, platform, architecture, download_url,
    checksum, checksum_type, file_size, release_notes, release_date,
    required, minimum_version, metadata, created_at,
    version_major, version_minor, version_patch, version_pre_release
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
ON CONFLICT (application_id, version, platform, architecture) DO UPDATE SET
    download_url        = EXCLUDED.download_url,
    checksum            = EXCLUDED.checksum,
    checksum_type       = EXCLUDED.checksum_type,
    file_size           = EXCLUDED.file_size,
    release_notes       = EXCLUDED.release_notes,
    release_date        = EXCLUDED.release_date,
    required            = EXCLUDED.required,
    minimum_version     = EXCLUDED.minimum_version,
    metadata            = EXCLUDED.metadata,
    version_major       = EXCLUDED.version_major,
    version_minor       = EXCLUDED.version_minor,
    version_patch       = EXCLUDED.version_patch,
    version_pre_release = EXCLUDED.version_pre_release
`

type UpsertReleaseParams struct {
	ID                string             `json:"id"`
	ApplicationID     string             `json:"application_id"`
	Version           string             `json:"version"`
	Platform          string             `json:"platform"`
	Architecture      string             `json:"architecture"`
	DownloadUrl       string             `json:"download_url"`
	Checksum          string             `json:"checksum"`
	ChecksumType      string             `json:"checksum_type"`
	FileSize          int64              `json:"file_size"`
	ReleaseNotes      pgtype.Text        `json:"release_notes"`
	ReleaseDate       pgtype.Timestamptz `json:"release_date"`
	Required          bool               `json:"required"`
	MinimumVersion    pgtype.Text        `json:"minimum_version"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	VersionMajor      int32              `json:"version_major"`
	VersionMinor      int32              `json:"version_minor"`
	VersionPatch      int32              `json:"version_patch"`
	VersionPreRelease pgtype.Text        `json:"version_pre_release"`
}

func (q *Queries) UpsertRelease(ctx context.Context, arg UpsertReleaseParams) error {
	_, err := q.db.Exec(ctx, upsertRelease,
		arg.ID,
		arg.ApplicationID,
		arg.Version,
		arg.Platform,
		arg.Architecture,
		arg.DownloadUrl,
		arg.Checksum,
		arg.ChecksumType,
		arg.FileSize,
		arg.ReleaseNotes,
		arg.ReleaseDate,
		arg.Required,
		arg.MinimumVersion,
		arg.Metadata,
		arg.CreatedAt,
		arg.VersionMajor,
		arg.VersionMinor,
		arg.VersionPatch,
		arg.VersionPreRelease,
	)
	return err
}
