// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package sqlcite

import (
	"context"
	"database/sql"
)

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = ?
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteApplication, id)
	return err
}

const getAllApplications = `-- name: GetAllApplications :many
SELECT id, name, description, platforms, config, created_at, updated_at
FROM applications
ORDER BY name
`

func (q *Queries) GetAllApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getAllApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Platforms,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, name, description, platforms, config, created_at, updated_at
FROM applications
WHERE id = ?
`

func (q *Queries) GetApplicationByID(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Platforms,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertApplication = `-- name: UpsertApplication :exec
INSERT INTO applications (id, name, description, platforms, config, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    platforms = excluded.platforms,
    config = excluded.config,
    updated_at = excluded.updated_at
`

type UpsertApplicationParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Platforms   string         `json:"platforms"`
	Config      string         `json:"config"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) UpsertApplication(ctx context.Context, arg UpsertApplicationParams) error {
	_, err := q.db.ExecContext(ctx, upsertApplication,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Platforms,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
