// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package sqlcite

import (
	"context"
	"database/sql"
)

const createApplication = `-- name: CreateApplication :exec
INSERT INTO applications (id, name, description, platforms, config, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateApplicationParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Platforms   string         `json:"platforms"`
	Config      string         `json:"config"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) error {
	_, err := q.db.ExecContext(ctx, createApplication,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Platforms,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = ?
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteApplication, id)
	return err
}

const getAllApplications = `-- name: GetAllApplications :many
SELECT id, name, description, platforms, config, created_at, updated_at
FROM applications
ORDER BY name
`

func (q *Queries) GetAllApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getAllApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Platforms,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, name, description, platforms, config, created_at, updated_at
FROM applications
WHERE id = ?
`

func (q *Queries) GetApplicationByID(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Platforms,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE applications
SET name = ?, description = ?, platforms = ?, config = ?, updated_at = ?
WHERE id = ?
`

type UpdateApplicationParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Platforms   string         `json:"platforms"`
	Config      string         `json:"config"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.ExecContext(ctx, updateApplication,
		arg.Name,
		arg.Description,
		arg.Platforms,
		arg.Config,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
