// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcite

import (
	"database/sql"
)

type ApiKey struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	KeyHash     string `json:"key_hash"`
	Prefix      string `json:"prefix"`
	Permissions string `json:"permissions"`
	Enabled     int64  `json:"enabled"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Application struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Platforms   string         `json:"platforms"`
	Config      string         `json:"config"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type Release struct {
	ID             string         `json:"id"`
	ApplicationID  string         `json:"application_id"`
	Version        string         `json:"version"`
	Platform       string         `json:"platform"`
	Architecture   string         `json:"architecture"`
	DownloadUrl    string         `json:"download_url"`
	Checksum       string         `json:"checksum"`
	ChecksumType   string         `json:"checksum_type"`
	FileSize       int64          `json:"file_size"`
	ReleaseNotes   sql.NullString `json:"release_notes"`
	ReleaseDate    string         `json:"release_date"`
	Required       bool           `json:"required"`
	MinimumVersion sql.NullString `json:"minimum_version"`
	Metadata       sql.NullString `json:"metadata"`
	CreatedAt      string         `json:"created_at"`
}
