// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package sqlcite

import (
	"context"
	"database/sql"
)

const deleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases
WHERE application_id = ? AND version = ? AND platform = ? AND architecture = ?
`

type DeleteReleaseParams struct {
	ApplicationID string `json:"application_id"`
	Version       string `json:"version"`
	Platform      string `json:"platform"`
	Architecture  string `json:"architecture"`
}

func (q *Queries) DeleteRelease(ctx context.Context, arg DeleteReleaseParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelease,
		arg.ApplicationID,
		arg.Version,
		arg.Platform,
		arg.Architecture,
	)
	return err
}

const getRelease = `-- name: GetRelease :one
SELECT id, application_id, version, platform, architecture, download_url,
       checksum, checksum_type, file_size, release_notes, release_date,
       required, minimum_version, metadata, created_at
FROM releases
WHERE application_id = ? AND version = ? AND platform = ? AND architecture = ?
`

type GetReleaseParams struct {
	ApplicationID string `json:"application_id"`
	Version       string `json:"version"`
	Platform      string `json:"platform"`
	Architecture  string `json:"architecture"`
}

func (q *Queries) GetRelease(ctx context.Context, arg GetReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, getRelease,
		arg.ApplicationID,
		arg.Version,
		arg.Platform,
		arg.Architecture,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.Platform,
		&i.Architecture,
		&i.DownloadUrl,
		&i.Checksum,
		&i.ChecksumType,
		&i.FileSize,
		&i.ReleaseNotes,
		&i.ReleaseDate,
		&i.Required,
		&i.MinimumVersion,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getReleaseByID = `-- name: GetReleaseByID :one
SELECT id, application_id, version, platform, architecture, download_url,
       checksum, checksum_type, file_size, release_notes, release_date,
       required, minimum_version, metadata, created_at
FROM releases
WHERE id = ?
`

func (q *Queries) GetReleaseByID(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByID, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.Platform,
		&i.Architecture,
		&i.DownloadUrl,
		&i.Checksum,
		&i.ChecksumType,
		&i.FileSize,
		&i.ReleaseNotes,
		&i.ReleaseDate,
		&i.Required,
		&i.MinimumVersion,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getReleasesByAppID = `-- name: GetReleasesByAppID :many
SELECT id, application_id, version, platform, architecture, download_url,
       checksum, checksum_type, file_size, release_notes, release_date,
       required, minimum_version, metadata, created_at
FROM releases
WHERE application_id = ?
ORDER BY release_date DESC
`

func (q *Queries) GetReleasesByAppID(ctx context.Context, applicationID string) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, getReleasesByAppID, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Version,
			&i.Platform,
			&i.Architecture,
			&i.DownloadUrl,
			&i.Checksum,
			&i.ChecksumType,
			&i.FileSize,
			&i.ReleaseNotes,
			&i.ReleaseDate,
			&i.Required,
			&i.MinimumVersion,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleasesByPlatformArch = `-- name: GetReleasesByPlatformArch :many
SELECT id, application_id, version, platform, architecture, download_url,
       checksum, checksum_type, file_size, release_notes, release_date,
       required, minimum_version, metadata, created_at
FROM releases
WHERE application_id = ? AND platform = ? AND architecture = ?
ORDER BY release_date DESC
`

type GetReleasesByPlatformArchParams struct {
	ApplicationID string `json:"application_id"`
	Platform      string `json:"platform"`
	Architecture  string `json:"architecture"`
}

func (q *Queries) GetReleasesByPlatformArch(ctx context.Context, arg GetReleasesByPlatformArchParams) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, getReleasesByPlatformArch, arg.ApplicationID, arg.Platform, arg.Architecture)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Version,
			&i.Platform,
			&i.Architecture,
			&i.DownloadUrl,
			&i.Checksum,
			&i.ChecksumType,
			&i.FileSize,
			&i.ReleaseNotes,
			&i.ReleaseDate,
			&i.Required,
			&i.MinimumVersion,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelease = `-- name: UpsertRelease :exec
INSERT INTO releases (
    id, application_id, version, platform, architecture, download_url,
    checksum, checksum_type, file_size, release_notes, release_date,
    required, minimum_version, metadata, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (application_id, version, platform, architecture) DO UPDATE SET
    id = excluded.id,
    download_url = excluded.download_url,
    checksum = excluded.checksum,
    checksum_type = excluded.checksum_type,
    file_size = excluded.file_size,
    release_notes = excluded.release_notes,
    release_date = excluded.release_date,
    required = excluded.required,
    minimum_version = excluded.minimum_version,
    metadata = excluded.metadata
`

type UpsertReleaseParams struct {
	ID             string         `json:"id"`
	ApplicationID  string         `json:"application_id"`
	Version        string         `json:"version"`
	Platform       string         `json:"platform"`
	Architecture   string         `json:"architecture"`
	DownloadUrl    string         `json:"download_url"`
	Checksum       string         `json:"checksum"`
	ChecksumType   string         `json:"checksum_type"`
	FileSize       int64          `json:"file_size"`
	ReleaseNotes   sql.NullString `json:"release_notes"`
	ReleaseDate    string         `json:"release_date"`
	Required       bool           `json:"required"`
	MinimumVersion sql.NullString `json:"minimum_version"`
	Metadata       sql.NullString `json:"metadata"`
	CreatedAt      string         `json:"created_at"`
}

func (q *Queries) UpsertRelease(ctx context.Context, arg UpsertReleaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertRelease,
		arg.ID,
		arg.ApplicationID,
		arg.Version,
		arg.Platform,
		arg.Architecture,
		arg.DownloadUrl,
		arg.Checksum,
		arg.ChecksumType,
		arg.FileSize,
		arg.ReleaseNotes,
		arg.ReleaseDate,
		arg.Required,
		arg.MinimumVersion,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}
